import { createAppAuth } from "@octokit/auth-app";
import { Octokit } from "@octokit/rest";
import { minimatch } from "minimatch";
import { Prisma } from "@prisma/client";
import { PRReviewResult } from "@pr-reviewer/shared";
import { prisma } from "../lib/prisma.js";

function createOctokit(installationId: number): Octokit {
  const privateKey = (process.env.GITHUB_PRIVATE_KEY ?? "").replace(
    /\\n/g,
    "\n"
  );
  return new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: process.env.GITHUB_APP_ID,
      privateKey,
      installationId,
    },
  });
}

async function getInstallationId(repoFullName: string): Promise<number> {
  const config = await prisma.repoConfig.findUnique({
    where: { repoFullName },
    select: { installationId: true },
  });
  if (!config) {
    throw new Error(`No config found for repo: ${repoFullName}`);
  }
  return config.installationId;
}

export async function fetchPRDiff(
  repoFullName: string,
  prNumber: number,
  ignorePaths: string[]
): Promise<string> {
  const installationId = await getInstallationId(repoFullName);
  const octokit = createOctokit(installationId);

  const [owner, repo] = repoFullName.split("/");

  const response = await octokit.rest.pulls.get({
    owner,
    repo,
    pull_number: prNumber,
    mediaType: { format: "diff" },
  });

  const rawDiff = response.data as unknown as string;

  if (ignorePaths.length === 0) return rawDiff;

  // Split diff into per-file sections and filter
  const sections = rawDiff.split(/(?=^diff --git )/m);
  const filtered = sections.filter((section) => {
    if (!section.startsWith("diff --git ")) return true;
    const match = section.match(/^diff --git a\/(.*?) b\//m);
    if (!match) return true;
    const filePath = match[1];
    return !ignorePaths.some((pattern) => minimatch(filePath, pattern));
  });

  return filtered.join("");
}

const severityEmoji: Record<string, string> = {
  critical: "🚨",
  warning: "⚠️",
  suggestion: "💡",
  praise: "✅",
};

function formatReviewAsMarkdown(review: PRReviewResult): string {
  const lines: string[] = [
    `## AI Code Review`,
    ``,
    `**Score:** ${review.score}/100`,
    ``,
    `### Summary`,
    review.summary,
    ``,
  ];

  if (review.comments.length > 0) {
    lines.push(`### Comments`);
    lines.push(``);
    for (const comment of review.comments) {
      const emoji = severityEmoji[comment.severity] ?? "•";
      const location =
        comment.filePath
          ? comment.lineNumber
            ? ` \`${comment.filePath}:${comment.lineNumber}\``
            : ` \`${comment.filePath}\``
          : "";
      lines.push(`${emoji} **${comment.severity.toUpperCase()}**${location}`);
      lines.push(``);
      lines.push(comment.message);
      lines.push(``);
    }
  }

  lines.push(`---`);
  lines.push(`*Generated by AI PR Reviewer at ${review.generatedAt}*`);

  return lines.join("\n");
}

export async function postReviewComment(
  repoFullName: string,
  prNumber: number,
  review: PRReviewResult
): Promise<void> {
  const installationId = await getInstallationId(repoFullName);
  const octokit = createOctokit(installationId);

  const [owner, repo] = repoFullName.split("/");
  const body = formatReviewAsMarkdown(review);

  await octokit.rest.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body,
  });

  await prisma.pRReview.upsert({
    where: { repoFullName_prNumber: { repoFullName, prNumber } },
    create: {
      repoFullName,
      prNumber,
      score: review.score,
      summary: review.summary,
      comments: review.comments as unknown as Prisma.InputJsonValue,
      generatedAt: new Date(review.generatedAt),
    },
    update: {
      score: review.score,
      summary: review.summary,
      comments: review.comments as unknown as Prisma.InputJsonValue,
      generatedAt: new Date(review.generatedAt),
    },
  });
}
